version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  labels:
  - automerge
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.36
    - 14.14.37
  - dependency-name: "@next/bundle-analyzer"
    versions:
    - 10.1.1
    - 10.1.2
  - dependency-name: preact-render-to-string
    versions:
    - 5.1.17
    - 5.1.18
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: husky
    versions:
    - 5.2.0
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 12.0.0
  - dependency-name: "@types/react"
    versions:
    - 17.0.2
  - dependency-name: next
    versions:
    - 10.0.6
